version: '3.8'

services:
  # Backend API Service
  prima-scholar-api:
    build: ./backend
    container_name: prima-scholar-api
    environment:
      - FLASK_ENV=production
      - TIDB_CONNECTION_STRING=${TIDB_CONNECTION_STRING}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - uploaded_documents:/app/uploads
    networks:
      - prima-scholar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Service
  prima-scholar-frontend:
    build: ./frontend
    container_name: prima-scholar-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ENVIRONMENT=production
    ports:
      - "3000:80"
    depends_on:
      - prima-scholar-api
    networks:
      - prima-scholar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: prima-scholar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prima-scholar-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional for production)
  nginx:
    image: nginx:alpine
    container_name: prima-scholar-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - prima-scholar-api
      - prima-scholar-frontend
    networks:
      - prima-scholar-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:
    driver: local
  uploaded_documents:
    driver: local

networks:
  prima-scholar-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16